### ISSUE TITLE
Queries browser new feature: duplicate query

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/MooseIDE#633] opened 2022-06-02 12:50 UTC
When creating several similar queries, it could be nice to be able to duplicate an existing query.
Then you have only to modify it slightly instead of recreating it from scratch.

Use case: when creating several intent tags with only different primitive values

**Comment by maxwills** [comment] 2022-10-28 14:55
We tried to take this issue for the sprint. But we need to clarify some points first.

We understand the idea of duplicating a query. However, it is not clear what happens when the Query has child queries.  
- If the parent query is duplicated, should the duplicate include a duplicate of all children? 
- Or if a child query is duplicated, should it be added to the same parent? or as an new first level query?

**Comment by NicolasAnquetil** [comment] 2022-11-05 07:32
I would say:
- don't duplicate the children of a duplicated query (which is a parent)
- duplicate a children in the same parent (seems to answers the scenario proposed by Clotilde)

But may be we don't need this feature (duplication). The scenario proposed by Clotilde can be solved by other solutions that Romain Degrave started to work on (see #696)

**Closed** 2022-11-05 07:32 UTC
