### ISSUE TITLE
Distribution Map settings requires to have the tag browser open

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MooseIDE#985] opened 2024-01-10 12:57 UTC
The Distribution Map settings are not working for the tags selection if the tag browser is not open which is really counter intuitive. 

I'll try to fix this but I prefer to keep a trace of the issue in case I do not fix this now.

**Comment by NicolasAnquetil** [comment] 2024-01-10 13:01
duplicate of #871

**Closed** 2024-01-12 15:02 UTC
Labels: bug
