### ISSUE TITLE
Playground command opens the Pharo Playground on Moose11

### ISSUE THREAD

**Issue by RomainDeg** [moosetechnology/MooseIDE#844] opened 2023-05-12 12:25 UTC
When pressing CTRL+O+W on a Moose11 image, the opened playground is the Pharo one, which does not have the 'Inspect in Moose' or 'Models' buttons.
There is also two different playgrounds item in the world menu (Moose -> Moose Playground) and (Browse -> Playground). Both of them open a Moose Playground.

**Comment by uNouss** [comment] 2023-05-26 08:38
the problem is not in moose but in pharo11. `MiPlayground` is correctly registered in the tool registry. However in pharo11, the shortcuts are not using the global registry. We fix that in https://github.com/pharo-project/pharo/pull/13819

**Comment by uNouss** [comment] 2023-05-26 08:39
this issue will be fixed when the pharo PR is integrated.

**Closed by uNouss** 2023-05-26 08:39 UTC
Labels: Sprint
